# Работа с тензорами в numpy
### https://numpy.org/
### Быстрый старт: https://numpy.org/devdocs/user/quickstart.html

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = np.array([0,1,2,3])
print(b)

[0 1 2 3]


In [4]:
print(f"a*b={a*b}")
print(f"a+b={a+b}")

a*b=[ 0  2  6 12]
a+b=[1 3 5 7]


In [5]:
# Сакалярное произведение
def dot(x, y):
    y_sum = 0.0
    for i in range(len(x)):
        y_sum = y_sum + x[i]*y[i]
    return y_sum

dot(a, b)

20.0

In [6]:
print(np.dot(a,b))
print(np.sum(a*b))

20
20


In [7]:
# Еще одно скалярное произведение
c = np.array([[1,2,3,4], [2,3,4,5]])
np.dot(c,a)

array([30, 40])

In [8]:
# Норма вектора
print(np.sqrt(np.dot(a, a)))

# https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
print(np.linalg.norm(a))

# Норма L1: max(sum(abs(x), axis=0))
print(np.linalg.norm(a, 1))


5.477225575051661
5.477225575051661
10.0


In [9]:
# Евклидова метрика
def e_dist(x: np.array, y: np.array) -> float:
     return np.linalg.norm(x - y)

# Манхэттенская метрика
def m_dist(x: np.array, y: np.array) -> float:
    return np.linalg.norm(x - y, 1)

print(f"e_dist(a, b) = {e_dist(a, b)}")
print(f"m_dist(a, b) = {m_dist(a, b)}")

e_dist(a, b) = 2.0
m_dist(a, b) = 4.0


In [10]:
# Единичная матрица, она же - ортонормированный базис в Евклидовом пространстве
basis = np.eye(4, 4)
print(f"basis=\n{basis}\n"+"-"*32)
print(f"{basis} * 2=\n{basis*2}\n"+"-"*32)
v = np.arange(1, 5)
print(f"{basis} * {v}=\n{basis*v}\n"+"-"*32)

basis=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] * 2=
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
--------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] * [1 2 3 4]=
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
--------------------------------


In [11]:
# Матрицы
A = np.arange(0, 32).reshape((4, 8))
B = np.arange(1, 33).reshape((8, 4))
C = np.arange(0, 16).reshape((4, 4))
A, B, C


(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [12]:
# Умножение матриц
print(A @ (B @ C))
# E = A @ B
# D = B @ C
# E @ C
# A @ D



[[ 15680  18200  20720  23240]
 [ 42304  49048  55792  62536]
 [ 68928  79896  90864 101832]
 [ 95552 110744 125936 141128]]


In [13]:
n = 8
m = 6
C = np.arange(0, n*m).reshape((n, m))
A @ C

array([[ 840,  868,  896,  924,  952,  980],
       [2184, 2276, 2368, 2460, 2552, 2644],
       [3528, 3684, 3840, 3996, 4152, 4308],
       [4872, 5092, 5312, 5532, 5752, 5972]])

In [19]:
# Соединение выходов элемента со входами
size = 4
# Единичная матрица соединяет элементы 1:1 без изменения порядка
M = np.eye(size)
print(f"M=\n{M}\n")

# Изменение порядка может быть сделано перестановкой столбцов матрицы
permute1 = [3, 2, 1, 0]
print(f"Обратный порядок: M[{permute1}]=\n{M[:, permute1]}\n")

permute2 = [1, 0, 2, 3]
print(f"1-й к 2-му, 2-й к 1-му: M[{permute2}]=\n{M[:, permute2]}")


M=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Обратный порядок: M[[3, 2, 1, 0]]=
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

1-й к 2-му, 2-й к 1-му: M[[1, 0, 2, 3]]=
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# При умножении на матрицу перестановок изменяется порядок элементов в векторе
size = 4
y1 = np.arange(4, 4+size)
M1 = M[:, permute1]
print(f"y1={y1}")
print(f"y1.M1={y1 @ M1}\n")

M2 = M[:, permute2]
print(f"y1={y1}")
print(f"y1.M2={y1 @ M2}")

y1=[4 5 6 7]
y1.M1=[7. 6. 5. 4.]

y1=[4 5 6 7]
y1.M2=[5. 4. 6. 7.]


In [25]:
# Обнуление одного из выходов - нулевая строка в матрице связей
M3 = M * np.array([1, 1, 1, 0])
print(f'M3={M3}')
print(f'y1.M3={y1 @ M3}')


M3=[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
y1.M3=[4. 5. 6. 0.]


In [30]:
M4 = np.arange(0, 2*5*3*4).reshape(2, 5, 3, 4)
# print(M4)
print(M4.flatten())
M4.flatten().shape



[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


(120,)

In [ ]:
def 