# Работа с тензорами в numpy
### https://numpy.org/
### Быстрый старт: https://numpy.org/devdocs/user/quickstart.html

In [7]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
b = np.array([0,1,2,3])
print(b)

[0 1 2 3]


In [9]:
print(f"a*b={a*b}")
print(f"a+b={a+b}")

a*b=[ 0  2  6 12]
a+b=[1 3 5 7]


In [10]:
def dot(x,y):
    y = 0.0
    for i in range(len(x)):
        y = y + x[i]*y[i]
    return y

In [11]:
print(np.dot(a,b))
print(np.sum(a*b))

20
20


In [12]:
c = np.array([[1,2,3,4], [2,3,4,5]])
np.dot(c,a)

array([30, 40])

In [13]:
# Норма вектора
print(np.sqrt(np.dot(a, a)))

# https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
print(np.linalg.norm(a))

# Норма L1: max(sum(abs(x), axis=0))
print(np.linalg.norm(a, 1))


5.477225575051661
5.477225575051661
10.0


In [14]:
# Евклидова метрика
def e_dist(x: np.array, y: np.array) -> float:
     return np.linalg.norm(x - y)

# Манхэттенская метрика
def m_dist(x: np.array, y: np.array) -> float:
    return np.linalg.norm(x - y, 1)

print(f"e_dist(a, b) = {e_dist(a, b)}")
print(f"m_dist(a, b) = {m_dist(a, b)}")

e_dist(a, b) = 2.0
m_dist(a, b) = 4.0


In [23]:
# Единичная матрица, она же - ортонормированный базис в Евклидовом пространстве
basis = np.eye(4,4)
print(f"basis=\n{basis}\n"+"-"*32)
print(f"{basis} * 2=\n{basis*2}\n"+"-"*32)
v = np.arange(1, 5)
print(f"{basis} * {v}=\n{basis*2}\n"+"-"*32)

basis=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] * 2=
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
--------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] * [1 2 3 4]=
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
--------------------------------


In [5]:
# Матрицы
A = np.arange(0, 16).reshape((4, 4))
B = np.arange(-8, 8).reshape((4, 4))
A, B


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[-8, -7, -6, -5],
        [-4, -3, -2, -1],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7]]))

In [8]:
# Умножение матриц
print(A @ B)

array([[ 132,  404,  676,  948],
       [ 164,  308,  452,  596],
       [ 196,  212,  228,  244],
       [ 228,  116,    4, -108]])

In [24]:
C = np.arange(0, 16).reshape((2, 8))
A @ C

NameError: name 'A' is not defined

In [8]:
import math

def sigmoid(z):
    return 1/(1+math.exp(-z))

for x in range(0,4):
    print(f"f({a[x]})={sigmoid(a[x])}")

f(1)=0.7310585786300049
f(2)=0.8807970779778823
f(3)=0.9525741268224334
f(4)=0.9820137900379085


In [10]:
sigmoid_v = np.vectorize(sigmoid)
print(a)
result = sigmoid_v(a)
print(result)


[1 2 3 4]
[0.73105858 0.88079708 0.95257413 0.98201379]


In [11]:
W1 = np.array(
[
    [0, 1, 2],
    [3, 2, 1],
    [2, 1,-2]
])
x1 = np.array([-2,3,1])
z = np.dot(x1,W1)
print(f"x1.W1={z}")
y1 = sigmoid_v(z)
print(f"sigmoid(x1.W1)={y1}")

x1.W1=[11  5 -3]
sigmoid(x1.W1)=[0.9999833  0.99330715 0.04742587]


In [13]:
W2 = np.array([
    [-2, 0],
    [1,  1],
    [-2, 1]
])
y2 = sigmoid_v(np.dot(y1,W2))
print(f"f(y1.W2)={y2}")

f(y1.W2)=[0.24945685 0.73899142]


In [18]:
a.shape

(4,)

In [19]:
W2=W2-a
print(W2)

ValueError: operands could not be broadcast together with shapes (3,2) (4,) 

In [14]:
W2 = W2 - 0.1
y2 = sigmoid_v(np.dot(y1,W2))
print(f"f(y1.W2)={y2}")

f(y1.W2)=[0.21322694 0.6977616 ]


In [13]:
y_true = np.array([0.0, 1.0])
error = np.sum(np.square(y_true-y2))
error

0.13681377620455265