# Работа с тензорами в numpy
### https://numpy.org/
### Быстрый старт: https://numpy.org/devdocs/user/quickstart.html

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
b = np.array([0,1,2,3])
print(b)

[0 1 2 3]


In [3]:
print(f"a*b={a*b}")
print(f"a+b={a+b}")

a*b=[ 0  2  6 12]
a+b=[1 3 5 7]


In [4]:
def dot(x,y):
    y = 0.0
    for i in range(len(x)):
        y = y + x[i]*y[i]
    return y

In [6]:
print(np.dot(a,b))
print(np.sum(a*b))

20
20


In [7]:
c = np.array([[1,2,3,4], [2,3,4,5]])
np.dot(c,a)

array([30, 40])

In [8]:
import math

def sigmoid(z):
    return 1/(1+math.exp(-z))

for x in range(0,4):
    print(f"f({a[x]})={sigmoid(a[x])}")

f(1)=0.7310585786300049
f(2)=0.8807970779778823
f(3)=0.9525741268224334
f(4)=0.9820137900379085


In [10]:
sigmoid_v = np.vectorize(sigmoid)
print(a)
result = sigmoid_v(a)
print(result)


[1 2 3 4]
[0.73105858 0.88079708 0.95257413 0.98201379]


In [11]:
W1 = np.array(
[
    [0, 1, 2],
    [3, 2, 1],
    [2, 1,-2]
])
x1 = np.array([-2,3,1])
z = np.dot(x1,W1)
print(f"x1.W1={z}")
y1 = sigmoid_v(z)
print(f"sigmoid(x1.W1)={y1}")

x1.W1=[11  5 -3]
sigmoid(x1.W1)=[0.9999833  0.99330715 0.04742587]


In [13]:
W2 = np.array([
    [-2, 0],
    [1,  1],
    [-2, 1]
])
y2 = sigmoid_v(np.dot(y1,W2))
print(f"f(y1.W2)={y2}")

f(y1.W2)=[0.24945685 0.73899142]


In [18]:
a.shape

(4,)

In [19]:
W2=W2-a
print(W2)

ValueError: operands could not be broadcast together with shapes (3,2) (4,) 

In [14]:
W2 = W2 - 0.1
y2 = sigmoid_v(np.dot(y1,W2))
print(f"f(y1.W2)={y2}")

f(y1.W2)=[0.21322694 0.6977616 ]


In [13]:
y_true = np.array([0.0, 1.0])
error = np.sum(np.square(y_true-y2))
error

0.13681377620455265