In [1]:
import numpy as np
import math

In [2]:
x = np.random.rand(2)
w = np.random.rand(2)
y = np.dot(x,w)
print(f" x={x}\n w={w}\n y={y}")

 x=[0.68827153 0.16268854]
 w=[0.41429678 0.90335977]
 y=0.43211496700290675


In [3]:
def get_angle(x, w):
    w_norm = np.sqrt(np.dot(w, w))
    x_norm = np.sqrt(np.dot(x, x))
    # Угол в градусах
    angle = math.acos(np.dot(w,x)/(w_norm*x_norm))/math.pi*180
    return angle

In [4]:
w = np.array([1.,0.])
x = np.array([3.,0.])
# Отношение двух векторов, как косинус угла между ними
angle = get_angle(w, x)
print(f"Угол между x и w: {angle}")


Угол между x и w: 0.0


In [5]:
count = 2
x = np.random.rand(count*2).reshape((count,2))*10
w = np.random.rand(2)*10
print(f"Координаты:\n x=\n{x}\n\n Веса синапсов: w={w}")


Координаты:
 x=
[[6.14798767 6.65058796]
 [5.44812611 8.31495431]]

 Веса синапсов: w=[9.2682421 6.3072889]


In [6]:
# Сделаем несколько кластеров данных - clusters
count = 32      # Количество векторов в выборке
clusters = 4    # Количество кластеров
size = 2        # Размерность вектора данных
x = 100.0*(np.random.rand(count*size).reshape((count, size)))
w = 100.0*(np.random.rand(clusters*size).reshape((clusters, size)))
print(f"x=\n{x} \n\n w={w}")


x=
[[85.32846996  1.8047225 ]
 [30.18342158 50.95615136]
 [99.73042433 63.02143297]
 [99.14962472 47.53482258]
 [53.75849892 13.72573134]
 [75.01991041 11.84661881]
 [ 1.32217472 89.25006889]
 [ 1.74288656 46.77537522]
 [79.00312388 81.02940258]
 [25.53147918 27.66401596]
 [53.89800187 89.70035142]
 [22.30261963 41.87634516]
 [41.74037355 73.33441081]
 [ 6.84014291 89.96473914]
 [ 8.59765646 65.51607842]
 [74.92123235 44.75218407]
 [25.39776593 86.48888179]
 [21.51923011 59.69792603]
 [62.18356581 51.3004736 ]
 [15.36493589 10.00578393]
 [86.41532585 22.00790852]
 [42.05380427 42.41338493]
 [16.77608683 84.44614234]
 [10.77526795 40.87381494]
 [12.96567246 15.50583422]
 [12.29264175 52.70355136]
 [73.42835317 16.12375914]
 [13.67035263 30.66135365]
 [45.99072622 22.15949812]
 [93.68106077 78.13413259]
 [14.51279635 29.11036413]
 [19.42306478 79.85708365]] 

 w=[[57.94155357 93.97177513]
 [97.03105317 30.9339686 ]
 [19.46999307 61.29950068]
 [49.7864966  75.51483896]]


In [7]:
# Теперь средний угол между центром кластера и векторами выборки
angle = np.zeros(clusters, dtype=np.float64)
dist = np.zeros(clusters, dtype=np.float64)
for i in range(32):
    # цикл по всем кластерам
    for c in range(clusters):
        dist[c] = 0
        angle[c] = 0
        # цикл по всем входным примерам
        for j in range(count):
            w[c] = w[c] + 0.01 * np.add(x[j],-w[c])
            dist[c] += np.sqrt(np.sum(np.power(x[j]-w[c],2)))
            angle[c] += get_angle(w[c], x[j])
        dist[c] /= count
        angle[c] /= size
    print(f"{i} distance={angle}")

# Из-за того что все векторы весов меняются одинаково быстро - все они приходят к центру тяжести всего набора точек

0 distance=[349.53343119 531.79268622 392.50814072 349.22453593]
1 distance=[349.30842514 471.61070558 365.72060308 348.98509091]
2 distance=[349.07577983 425.40002023 352.07272155 348.76529544]
3 distance=[348.85330756 397.04934593 349.20418798 348.57472092]
4 distance=[348.65378309 378.55633933 348.8342833  348.41670664]
5 distance=[348.48381024 368.25510429 348.57017735 348.29012017]
6 distance=[348.34473416 360.43526952 348.38153718 348.19132125]
7 distance=[348.23441405 355.07476397 348.24651639 348.11570231]
8 distance=[348.14893718 351.80139878 348.14963494 348.05865883]
9 distance=[348.08386502 350.21865571 348.07996015 348.01608621]
10 distance=[348.03497023 349.10165944 348.02975532 347.98456236]
11 distance=[347.99858378 348.66787601 347.99352433 347.96135376]
12 distance=[347.97169696 348.41887953 347.96734683 347.94433867]
13 distance=[347.95193239 348.23798088 347.94841623 347.93190239]
14 distance=[347.93745828 348.10663407 347.93471716 347.92283296]
15 distance=[347.926

In [18]:
# Сделаем несколько кластеров данных - clusters
count = 8      # Количество векторов в выборке
clusters = 4    # Количество кластеров
size = 2        # Размерность вектора данных
iter_count = 64
x = 100.0*(np.random.rand(count*size).reshape((count, size))*2-1)
w = 100.0*(np.random.rand(clusters*size).reshape((clusters, size))*2-1)
print(f"x={x} \n\n w={w}\n")
angle = np.zeros(clusters, dtype=np.float64)
for i in range(iter_count):
    # цикл по всем кластерам
    d = np.zeros(clusters, dtype=np.float64)
    for c in range(clusters):
        # angle[c] = 0
        # цикл по всем 
        for j in range(count):
            dist = np.linalg.norm(x[j]-w[c])
            alpha =np.exp(-(dist*dist))
            w[c] = w[c] + alpha * np.add(x[j], -w[c]) 
            angle[c] += get_angle(w[c], x[j])
            d[c] += dist
        d[c] /= count
        angle[c] /= count
    # print(f"{i} a={angle} d={d}")
print(f"x={x} \n\n w={w}\n")

x=[[-35.75027201 -67.47102272]
 [-27.66026498  24.39423206]
 [-12.60645248 -42.81000337]
 [ -7.92876053  47.6541944 ]
 [ 59.26200741 -22.04940998]
 [-12.63716913  60.73098656]
 [-79.31796003  57.19175756]
 [-97.37802735 -44.64251455]] 

 w=[[-11.99298127 -39.44682751]
 [ 16.26187907 -92.27106975]
 [-52.29777811 -98.78313004]
 [-83.22646373  86.58124469]]

x=[[-35.75027201 -67.47102272]
 [-27.66026498  24.39423206]
 [-12.60645248 -42.81000337]
 [ -7.92876053  47.6541944 ]
 [ 59.26200741 -22.04940998]
 [-12.63716913  60.73098656]
 [-79.31796003  57.19175756]
 [-97.37802735 -44.64251455]] 

 w=[[-11.99331303 -39.44864631]
 [ 16.26187907 -92.27106975]
 [-52.29777811 -98.78313004]
 [-83.22646373  86.58124469]]



In [9]:
print(f"\n\n w={w}\n")



 w=[[ 59.72707853 -38.71062722]
 [ 57.35334968  52.86806676]
 [ 20.50080775 -78.12074891]
 [  8.15288324  10.54190384]]



In [10]:
# Функция сигмоиды
def sigmoid(z):
    z = 1/(1+np.exp(-z))
    return z

In [11]:
# Выход сети для
f = np.vectorize(sigmoid)
x0 = np.random.rand(size).reshape((size))
y = np.zeros(clusters, dtype=np.float64)
for c in range(clusters):
    y[c] = np.dot(x0, w[c])
print(f"x={x0} \n y={y} \n w={w}")


x=[0.99553942 0.70240485] 
 y=[ 32.27012903  94.23230696 -34.46303043  15.52120103] 
 w=[[ 59.72707853 -38.71062722]
 [ 57.35334968  52.86806676]
 [ 20.50080775 -78.12074891]
 [  8.15288324  10.54190384]]


In [19]:
outputs = np.zeros(y.shape[0], dtype=np.float64)
outputs[np.argmax(y)] = 1.0
print(f"outputs={outputs}")

outputs=[0. 1. 0. 0.]


In [20]:
def softmax(x):
    exp = np.exp(x)
    e_x = exp / np.sum(exp)
    return e_x

In [14]:
# Выход сети для
f = np.vectorize(sigmoid)
# softmax_v = np.vectorize(softmax)
x0 = np.random.rand(size).reshape((size))
y = np.zeros(clusters, dtype=np.float64)
for c in range(clusters):
    y[c] = np.dot(w[c], x0)
print(f"x={x0}")
print(f"y={y}")
s = softmax(y)
print(f"softmax(y)={s} \n sum(softmax(x))={np.sum(s)}")

x=[0.70581672 0.1087992 ]
y=[37.94468554 46.23295684  5.97033782  6.90139206]
softmax(y)=[2.51385556e-04 9.99748614e-01 3.26631109e-18 8.28722754e-18] 
 sum(softmax(x))=1.0


In [22]:
vector=np.array([2.0, 3.0, -1, 5])
exp=np.exp(vector)
probability=exp/np.sum(exp)
print("Распределение вероятности:",probability)

Распределение вероятности: [0.04192238 0.11395685 0.00208719 0.84203357]


In [16]:
import torch
import torch.nn as nn

In [17]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
print(output)
print(output.sum(dim=1))



tensor([[0.2703, 0.3905, 0.3392],
        [0.0770, 0.5405, 0.3826]])
tensor([1., 1.])
